project:
  type: website
  render: ['README.qmd', 'sections/*.ipynb']

website:
  title: 'Deslocamento de Gestantes'
  description: 'Redes de deslocamento para acesso ao parto hospitalar no Brasil'
  sidebar:
    search: true
    style: "docked"
    background: info
    tools:
      - icon: github
        href: https://github.com/lucaslopes/gestantes
    contents:
      - README.qmd
      - section: 'Coleta de Dados'
        contents:
          - sections/database_sih.ipynb
          - sections/database_cnes.ipynb
          - sections/database_municipios.ipynb
          - sections/database_indicadores.ipynb
          - sections/database_dists.ipynb
          - sections/database_gmaps.ipynb
      - section: 'Tabelas Criadas'
        contents:
          - sections/table_locs.ipynb
          - sections/table_dslc.ipynb
          - sections/table_procs.ipynb
          - sections/table_counts.ipynb
          - sections/table_flux.ipynb
      - section: 'Resultados'
        contents:
          - sections/result.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
